export const FUNNELS = [
  {
    id: 'autonomous-infra',
    componentName: 'AutonomousInfra',
    name: 'Autonomous Infra',
    persona: 'Autonomous Infra Builder',
    color: '#0400D6',
    emoji: '🦾',
    tagline: 'Build your own infra. Own your own infra.',
    lead: 'Autonolas provides flexible, modular tools for you to build, own and run your own decentralized off-chain infrastructure.',
    cta: {
      btnText: 'Discuss Project Requirements',
      href: 'https://calendly.com/oaksprout/flexi-30',
    },
  },
  {
    id: 'smart-products',
    componentName: 'SmartProducts',
    name: 'Smart Products',
    persona: 'Smart Product Builder',
    color: '#D60000',
    emoji: '📈',
    tagline: 'Expand Your Market',
    lead: 'Build novel, accessible, marketing-expanding apps by leveraging crypto’s next breakthrough innovation: decentralized, autonomous off-chain services.',
    cta: {
      btnText: 'Discuss Project Requirements',
      href: 'https://calendly.com/oaksprout/flexi-30',
    },
  },
  {
    id: 'dao-autonomy',
    componentName: 'DAOAutonomy',
    name: 'DAO Autonomy',
    persona: 'DAO Autonomizer',
    color: '#44D600',
    emoji: '⚙',
    tagline: 'Make Your DAO Effective. Make Your DAO Autonomous.',
    lead: 'Gain a competitive edge through rich human coordination and decentralized, software-based operations.',
    cta: {
      btnText: 'Discuss Project Requirements',
      href: 'https://calendly.com/oaksprout/flexi-30',
    },
  },
  {
    id: 'autonomous-contributors',
    componentName: 'AutonomousContributors',
    name: 'Autonomous Contributors',
    persona: 'Autonomous Contributor',
    color: '#D6CD00',
    emoji: '🙋‍♂️',
    tagline: 'Become an Autonomous Contributor',
    lead: '',
    cta: {
      btnText: 'Start Earning Contribution Points',
      href: '/blog/30',
    },
  },
  {
    id: 'autonomous-developers',
    componentName: 'AutonomousDevelopers',
    name: 'Autonomous Developers',
    persona: 'Autonomous Developer',
    color: '#7200D6',
    emoji: '🧑‍💻',
    tagline: 'Become an Autonomous Developer',
    lead: 'Get qualified, receive engagements and build cutting-edge, impactful, autonomous systems.',
    cta: {
      btnText: 'Join the Academy',
      href: '/academy',
    },
  },
];
